### ISSUE TITLE
Need tutorial to create simple scala.js react app

### ISSUE THREAD

**Issue by anildigital** [xored/scala-js-react#13]
I am trying to create Simple Hello World scala-js-react app. But somehow I am not able to make it work.

It would be great if you publish a simple standalone Hello World example for this project.

I am basically struggling in setting up build.sbt, project/plugins.sbt. 

Thanks.

**Comment by kanterov** [comment]
Ok, I will but it into my TODO list.

**Comment by anildigital** [comment]
@kanterov Also getting this error https://gist.github.com/anildigital/9ed6de51a91bdba1bf0f for the project having just build.sbt and project/plugins.sbt

**Comment by kanterov** [comment]
Have you put this line into `project/plugins.sbt`?
```
addSbtPlugin("org.scala-lang.modules.scalajs" % "scalajs-sbt-plugin" % "0.5.3")
```

**Comment by kanterov** [comment]
I've implemented example app, https://github.com/xored/scala-js-react-example

**Comment by anildigital** [comment]
Awesome thanks ❤️

**Comment by anildigital** [comment]
Where is built.sbt in https://github.com/xored/scala-js-react-example as mentioned in Quickstart?

**Comment by kanterov** [comment]
It uses full build definiton of sbt, please refer to http://www.scala-sbt.org/0.13/tutorial/Full-Def.html
