### ISSUE TITLE
Missing setProps in ReactComponent

### ISSUE THREAD

**Issue by sergiusignacius** [xored/scala-js-react#8]
Hi! First of all, great job on implementing this port of React, it's really useful. :)

I was wondering: is there a setProps method missing in the current version, or if there is an alternative way to achieve the same result as calling it in the library?

Thanks,
Sérgio

**Comment by kanterov** [comment]
@sergiusignacius did it work for you?

**Comment by kanterov** [comment]
Closing due to reporter inactivity.
